# Generated by Django 6.0.4 on 2026-04-10 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nlp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breathing", "Breathing Exercise"),
                            ("motivation", "Motivational Message"),
                            ("calming", "Calming Technique"),
                            ("gratitude", "Gratitude Exercise"),
                            ("physical", "Physical Activity"),
                            ("social", "Social Connection"),
                            ("professional", "Professional Help"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("action_steps", models.TextField()),
                ("is_crisis_recommendation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emotion_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="nlp.emotionanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations",
            },
        ),
    ]
