# Generated by Django 6.0.4 on 2026-04-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dominant_emotion",
                    models.CharField(
                        choices=[
                            ("joy", "Joy"),
                            ("sadness", "Sadness"),
                            ("anger", "Anger"),
                            ("fear", "Fear"),
                            ("love", "Love"),
                            ("surprise", "Surprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joy_score", models.FloatField(default=0.0)),
                ("sadness_score", models.FloatField(default=0.0)),
                ("anger_score", models.FloatField(default=0.0)),
                ("fear_score", models.FloatField(default=0.0)),
                ("love_score", models.FloatField(default=0.0)),
                ("surprise_score", models.FloatField(default=0.0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("is_crisis", models.BooleanField(default=False)),
                ("raw_text", models.TextField()),
                ("processed_text", models.TextField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emotion_analysis",
                        to="journal.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "emotion_analysis",
            },
        ),
    ]
